---
- name: Converge
  hosts: all
  become: true
  vars:
    dns_domains:
      auth:
        scopedToken: "${MOLECULE_CF_TOKEN:-}"
      domains:
      - name: "${MOLECULE_CF_DOMAIN_NAME:-}"
        type: A
        proxied: true
        create: true
        zoneId: "${MOLECULE_CF_ZONE_ID:-}"

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
    - name: Install python requests
      pip:
        name: 
          - requests
  roles:
    - role: laurivan.cloudflare_ddns
  post_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
